version: 0.2
phases:
  pre_build:
    commands:
      - echo 'pre build is staring'
      - mvn clean
  install:
    commands:
      - echo 'install phase is staring'
      - mvn install
      - echo 'install phase finished'
  build:
    commands:
      - mvn package

artifacts:
    name: api.jar
    files:
      - target/api-1.0.0.jar
