server:
  port: 5000

spring:
  jpa:
    database: postgresql
    properties:
      hibernet:
        default-schema: public

  datasource:
    url: jdbc-secretsmanager:postgresql://testdb.cbw1gbfiqm3p.us-east-1.rds.amazonaws.com:5432/postgres
    username: dev/db/secret
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
